export const ROLE_ICONS = [
  'shield-account', 'doctor', 'account-heart', 'account', 'cog', 'medical-bag', 
  'hospital-building', 'heart-pulse', 'stethoscope', 'pill', 'bandage', 
  'wheelchair-accessibility', 'brain', 'run', 'walk', 'bike', 'yoga', 
  'nutrition', 'water', 'sleep', 'clock', 'calendar-check', 'clipboard-list', 
  'file-document', 'email', 'phone', 'map-marker', 'camera', 'microphone', 'video'
];


const _WELLNESS_ICONS = [
  'heart',
  'heart-pulse',
  'brain',
  'meditation',
  'yoga',
  'run',
  'walk',
  'bike',
  'dumbbell',
  'arm-flex',
  'weight-lifter',
  'human-handsup',
  'human-male-height',
  'human-female',
  'sleep',
  'bed',
  'water',
  'food-apple',
  'leaf',
  'flower',
  'pill',
  'stethoscope',
  'medical-bag',
  'hospital-box',
  'calendar-heart',
  'clock-outline',
  'play-circle',
  'video',
  'camera-outline',
  'heart-outline',
  'heart-plus',
  'pulse',
  'lungs',
  'tooth',
  'eye',
  'ear-hearing',
  'hand-heart',
  'hiking',
  'swim',
  'tennis',
  'basketball',
  'soccer',
  'karate',
  'ski',
  'rowing',
  'emoticon-happy-outline',
  'emoticon-sad-outline',
  'weather-sunny',
  'weather-night',
  'food',
  'food-fork-drink',
  'fruit-cherries',
  'carrot',
  'fish',
  'cup-water',
  'spa',
  'candle',
  'music',
  'book-open-page-variant',
  'clipboard-text',
  'chart-line',
  'chart-timeline',
  'thermometer',
  'needle',
  'alarm-check',
];

export const WELLNESS_ICONS = [...new Set(_WELLNESS_ICONS)];