"""restore_steps_in_wellness

Revision ID: 130adf908fb0
Revises: de073083540a
Create Date: 2026-06-15 20:08:09.972800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '130adf908fb0'
down_revision = 'de073083540a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wellness_sessions', sa.Column('steps', sa.JSON(), nullable=True))
    
    # Populate with empty JSON list
    op.execute("UPDATE wellness_sessions SET steps = '[]'")
    
    op.alter_column('wellness_sessions', 'steps', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wellness_sessions', 'steps')
    # ### end Alembic commands ###
