"""refactor_video_mapping

Revision ID: 16c38f75bcb7
Revises: 8f6088286de5
Create Date: 2026-06-15 16:08:03.884794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16c38f75bcb7'
down_revision = '8f6088286de5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_group_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_group_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['video_group_id'], ['video_groups.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('videos_video_group_id_fkey'), 'videos', type_='foreignkey')
    op.drop_column('videos', 'sort_order')
    op.drop_column('videos', 'video_group_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('video_group_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('videos', sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('videos_video_group_id_fkey'), 'videos', 'video_groups', ['video_group_id'], ['id'])
    op.drop_table('video_group_mappings')
    # ### end Alembic commands ###
