"""remove_key_and_steps_from_wellness_sessions

Revision ID: 21eed69bbd76
Revises: b0193b420458
Create Date: 2026-06-15 19:55:54.927100

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '21eed69bbd76'
down_revision = 'b0193b420458'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('wellness_sessions_key_key'), 'wellness_sessions', type_='unique')
    op.drop_column('wellness_sessions', 'key')
    op.drop_column('wellness_sessions', 'steps')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wellness_sessions', sa.Column('steps', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('wellness_sessions', sa.Column('key', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('wellness_sessions_key_key'), 'wellness_sessions', ['key'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
