"""add_chat_question_id_to_quick_relief

Revision ID: 47546d8e3ada
Revises: 481d7800b3fd
Create Date: 2026-06-15 16:49:51.819255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47546d8e3ada'
down_revision = '481d7800b3fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quick_reliefs', sa.Column('chat_question_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'quick_reliefs', 'chat_questions', ['chat_question_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quick_reliefs', type_='foreignkey')
    op.drop_column('quick_reliefs', 'chat_question_id')
    # ### end Alembic commands ###
