"""remove_key_from_videos

Revision ID: 481d7800b3fd
Revises: 73dcd55b16b5
Create Date: 2026-06-15 16:33:11.396230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '481d7800b3fd'
down_revision = '73dcd55b16b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('video_groups_key_key'), 'video_groups', type_='unique')
    op.drop_column('video_groups', 'key')
    op.drop_constraint(op.f('videos_key_key'), 'videos', type_='unique')
    op.drop_column('videos', 'key')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('key', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('videos_key_key'), 'videos', ['key'], postgresql_nulls_not_distinct=False)
    op.add_column('video_groups', sa.Column('key', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('video_groups_key_key'), 'video_groups', ['key'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
