"""'refactor_therapy_sessions_table'

Revision ID: 856c85ff7105
Revises: 3dd4064aaacb
Create Date: 2026-06-16 10:14:47.865898

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '856c85ff7105'
down_revision = '3dd4064aaacb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('therapy_sessions', sa.Column('group_id', sa.Integer(), nullable=False))
    op.add_column('therapy_sessions', sa.Column('video_id', sa.Integer(), nullable=False))
    op.add_column('therapy_sessions', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('therapy_sessions', sa.Column('created_by', sa.Integer(), nullable=False))
    op.add_column('therapy_sessions', sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('therapy_sessions', sa.Column('modified_by', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_therapy_sessions_user_completed'), table_name='therapy_sessions')
    op.create_index('ix_therapy_sessions_user_group_video', 'therapy_sessions', ['user_id', 'group_id', 'video_id'], unique=False)
    op.create_foreign_key(None, 'therapy_sessions', 'users', ['modified_by'], ['id'])
    op.create_foreign_key(None, 'therapy_sessions', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'therapy_sessions', 'videos', ['video_id'], ['id'])
    op.create_foreign_key(None, 'therapy_sessions', 'video_groups', ['group_id'], ['id'])
    op.drop_column('therapy_sessions', 'completed_at')
    op.drop_column('therapy_sessions', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('therapy_sessions', sa.Column('title', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.add_column('therapy_sessions', sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'therapy_sessions', type_='foreignkey')
    op.drop_constraint(None, 'therapy_sessions', type_='foreignkey')
    op.drop_constraint(None, 'therapy_sessions', type_='foreignkey')
    op.drop_constraint(None, 'therapy_sessions', type_='foreignkey')
    op.drop_index('ix_therapy_sessions_user_group_video', table_name='therapy_sessions')
    op.create_index(op.f('ix_therapy_sessions_user_completed'), 'therapy_sessions', ['user_id', 'completed_at'], unique=False)
    op.drop_column('therapy_sessions', 'modified_by')
    op.drop_column('therapy_sessions', 'modified_at')
    op.drop_column('therapy_sessions', 'created_by')
    op.drop_column('therapy_sessions', 'is_active')
    op.drop_column('therapy_sessions', 'video_id')
    op.drop_column('therapy_sessions', 'group_id')
    # ### end Alembic commands ###
