"""add audit fields to remaining business tables

Revision ID: a784ffed457e
Revises: 881ee87d7d95
Create Date: 2026-06-17 15:25:59.496631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a784ffed457e'
down_revision = '881ee87d7d95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('appointments', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('appointments', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('appointments', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('awards', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('awards', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('awards', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('awards', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('awards', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('chat_options', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('chat_options', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('chat_options', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('chat_options', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('chat_options', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('chat_questions', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('clinics', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('clinics', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('clinics', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('clinics', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('clinics', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('consultation_types', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('consultation_types', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('consultation_types', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('consultation_types', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('consultation_types', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('payments', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('payments', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('payments', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('quick_reliefs', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('quick_reliefs', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('relief_sessions', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('relief_sessions', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('user_preferences', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('user_preferences', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('user_preferences', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'updated_by')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_by')
    op.drop_column('user_preferences', 'is_active')
    op.drop_column('user_preferences', 'updated_by')
    op.drop_column('user_preferences', 'created_by')
    op.drop_column('relief_sessions', 'updated_by')
    op.drop_column('relief_sessions', 'created_by')
    op.drop_column('quick_reliefs', 'updated_by')
    op.drop_column('quick_reliefs', 'created_by')
    op.drop_column('payments', 'is_active')
    op.drop_column('payments', 'updated_by')
    op.drop_column('payments', 'created_by')
    op.drop_column('consultation_types', 'updated_by')
    op.drop_column('consultation_types', 'updated_at')
    op.drop_column('consultation_types', 'created_by')
    op.drop_column('consultation_types', 'created_at')
    op.drop_column('consultation_types', 'is_active')
    op.drop_column('clinics', 'updated_by')
    op.drop_column('clinics', 'updated_at')
    op.drop_column('clinics', 'created_by')
    op.drop_column('clinics', 'created_at')
    op.drop_column('clinics', 'is_active')
    op.drop_column('chat_questions', 'is_active')
    op.drop_column('chat_options', 'updated_by')
    op.drop_column('chat_options', 'updated_at')
    op.drop_column('chat_options', 'created_by')
    op.drop_column('chat_options', 'created_at')
    op.drop_column('chat_options', 'is_active')
    op.drop_column('awards', 'updated_by')
    op.drop_column('awards', 'updated_at')
    op.drop_column('awards', 'created_by')
    op.drop_column('awards', 'created_at')
    op.drop_column('awards', 'is_active')
    op.drop_column('appointments', 'updated_by')
    op.drop_column('appointments', 'updated_at')
    op.drop_column('appointments', 'created_by')
    op.drop_column('appointments', 'is_active')
    # ### end Alembic commands ###
