"""refactor_wellness_sessions

Revision ID: b0193b420458
Revises: 47546d8e3ada
Create Date: 2026-06-15 19:47:39.689851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0193b420458'
down_revision = '47546d8e3ada'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wellness_sessions', sa.Column('duration', sa.String(length=30), nullable=True))
    op.add_column('wellness_sessions', sa.Column('video_group_id', sa.Integer(), nullable=True))
    op.add_column('wellness_sessions', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('wellness_sessions', sa.Column('updated_by', sa.Integer(), nullable=True))
    
    # Data migration
    op.execute("UPDATE wellness_sessions SET duration = duration_label")
    op.execute("UPDATE wellness_sessions SET created_by = 1, updated_by = 1 WHERE created_by IS NULL")
    
    op.alter_column('wellness_sessions', 'duration', nullable=False)
    op.alter_column('wellness_sessions', 'created_by', nullable=False)
    op.alter_column('wellness_sessions', 'updated_by', nullable=False)

    op.create_foreign_key(None, 'wellness_sessions', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'wellness_sessions', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'wellness_sessions', 'video_groups', ['video_group_id'], ['id'])
    op.drop_column('wellness_sessions', 'video_url')
    op.drop_column('wellness_sessions', 'total_cycles')
    op.drop_column('wellness_sessions', 'duration_label')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wellness_sessions', sa.Column('duration_label', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.add_column('wellness_sessions', sa.Column('total_cycles', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('wellness_sessions', sa.Column('video_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'wellness_sessions', type_='foreignkey')
    op.drop_constraint(None, 'wellness_sessions', type_='foreignkey')
    op.drop_constraint(None, 'wellness_sessions', type_='foreignkey')
    op.drop_column('wellness_sessions', 'updated_by')
    op.drop_column('wellness_sessions', 'created_by')
    op.drop_column('wellness_sessions', 'video_group_id')
    op.drop_column('wellness_sessions', 'duration')
    # ### end Alembic commands ###
