"""refactor_mapping_tables_to_doctor_id

Revision ID: 0ed7998f0ebc
Revises: b0abccaf510c
Create Date: 2026-06-17 17:18:44.788650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ed7998f0ebc'
down_revision = 'b0abccaf510c'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    for table in ('doctor_expertise_mapping', 'doctor_language_mapping', 'doctor_speciality_mapping'):
        cols = {c['name'] for c in inspector.get_columns(table)}
        if 'doctor_id' not in cols:
            op.add_column(table, sa.Column('doctor_id', sa.Integer(), nullable=True))
            op.execute(f'UPDATE {table} SET doctor_id = (SELECT id FROM doctors WHERE doctors.user_id = {table}.user_id)')
            op.alter_column(table, 'doctor_id', nullable=False)
            op.drop_constraint(op.f(f'{table}_user_id_fkey'), table, type_='foreignkey')
            op.create_foreign_key(None, table, 'doctors', ['doctor_id'], ['id'])
        if 'user_id' in cols:
            op.drop_column(table, 'user_id')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_speciality_mapping', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'doctor_speciality_mapping', type_='foreignkey')
    op.create_foreign_key(op.f('doctor_speciality_mapping_user_id_fkey'), 'doctor_speciality_mapping', 'users', ['user_id'], ['id'])
    op.drop_column('doctor_speciality_mapping', 'doctor_id')
    op.add_column('doctor_language_mapping', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'doctor_language_mapping', type_='foreignkey')
    op.create_foreign_key(op.f('doctor_language_mapping_user_id_fkey'), 'doctor_language_mapping', 'users', ['user_id'], ['id'])
    op.drop_column('doctor_language_mapping', 'doctor_id')
    op.add_column('doctor_expertise_mapping', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'doctor_expertise_mapping', type_='foreignkey')
    op.create_foreign_key(op.f('doctor_expertise_mapping_user_id_fkey'), 'doctor_expertise_mapping', 'users', ['user_id'], ['id'])
    op.drop_column('doctor_expertise_mapping', 'doctor_id')
    # ### end Alembic commands ###
