"""refactor_mapping_tables_to_doctor_id

Revision ID: 0ed7998f0ebc
Revises: b0abccaf510c
Create Date: 2026-06-17 17:18:44.788650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ed7998f0ebc'
down_revision = 'b0abccaf510c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Doctor Expertise Mapping
    op.add_column('doctor_expertise_mapping', sa.Column('doctor_id', sa.Integer(), nullable=True))
    op.execute('UPDATE doctor_expertise_mapping SET doctor_id = (SELECT id FROM doctors WHERE doctors.user_id = doctor_expertise_mapping.user_id)')
    op.alter_column('doctor_expertise_mapping', 'doctor_id', nullable=False)
    op.drop_constraint(op.f('doctor_expertise_mapping_user_id_fkey'), 'doctor_expertise_mapping', type_='foreignkey')
    op.create_foreign_key(None, 'doctor_expertise_mapping', 'doctors', ['doctor_id'], ['id'])
    op.drop_column('doctor_expertise_mapping', 'user_id')
    
    # 2. Doctor Language Mapping
    op.add_column('doctor_language_mapping', sa.Column('doctor_id', sa.Integer(), nullable=True))
    op.execute('UPDATE doctor_language_mapping SET doctor_id = (SELECT id FROM doctors WHERE doctors.user_id = doctor_language_mapping.user_id)')
    op.alter_column('doctor_language_mapping', 'doctor_id', nullable=False)
    op.drop_constraint(op.f('doctor_language_mapping_user_id_fkey'), 'doctor_language_mapping', type_='foreignkey')
    op.create_foreign_key(None, 'doctor_language_mapping', 'doctors', ['doctor_id'], ['id'])
    op.drop_column('doctor_language_mapping', 'user_id')
    
    # 3. Doctor Speciality Mapping
    op.add_column('doctor_speciality_mapping', sa.Column('doctor_id', sa.Integer(), nullable=True))
    op.execute('UPDATE doctor_speciality_mapping SET doctor_id = (SELECT id FROM doctors WHERE doctors.user_id = doctor_speciality_mapping.user_id)')
    op.alter_column('doctor_speciality_mapping', 'doctor_id', nullable=False)
    op.drop_constraint(op.f('doctor_speciality_mapping_user_id_fkey'), 'doctor_speciality_mapping', type_='foreignkey')
    op.create_foreign_key(None, 'doctor_speciality_mapping', 'doctors', ['doctor_id'], ['id'])
    op.drop_column('doctor_speciality_mapping', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_speciality_mapping', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'doctor_speciality_mapping', type_='foreignkey')
    op.create_foreign_key(op.f('doctor_speciality_mapping_user_id_fkey'), 'doctor_speciality_mapping', 'users', ['user_id'], ['id'])
    op.drop_column('doctor_speciality_mapping', 'doctor_id')
    op.add_column('doctor_language_mapping', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'doctor_language_mapping', type_='foreignkey')
    op.create_foreign_key(op.f('doctor_language_mapping_user_id_fkey'), 'doctor_language_mapping', 'users', ['user_id'], ['id'])
    op.drop_column('doctor_language_mapping', 'doctor_id')
    op.add_column('doctor_expertise_mapping', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'doctor_expertise_mapping', type_='foreignkey')
    op.create_foreign_key(op.f('doctor_expertise_mapping_user_id_fkey'), 'doctor_expertise_mapping', 'users', ['user_id'], ['id'])
    op.drop_column('doctor_expertise_mapping', 'doctor_id')
    # ### end Alembic commands ###
