"""Add SlotTimings model

Revision ID: 27abcfbe7b05
Revises: e0b33d6828f1
Create Date: 2026-06-18 10:33:25.389887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27abcfbe7b05'
down_revision = 'e0b33d6828f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slot_timings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('day_of_week_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['day_of_week_id'], ['days_of_week.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slot_timings')
    # ### end Alembic commands ###
