"""Added is default column in roles

Revision ID: 29d9dc6c6b4a
Revises: 4a3fb0eadafa
Create Date: 2026-06-18 10:03:15.994478

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '29d9dc6c6b4a'
down_revision = '4a3fb0eadafa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('appointments', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('appointments', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('appointments', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('awards', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('awards', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('awards', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('awards', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('awards', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('chat_options', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('chat_options', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('chat_options', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('chat_options', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('chat_options', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('chat_questions', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('clinics', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('clinics', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('clinics', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('clinics', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('clinics', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('payments', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('payments', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('payments', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('quick_reliefs', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('quick_reliefs', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('relief_sessions', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('relief_sessions', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('roles', sa.Column('is_default', sa.Boolean(), nullable=True))
    op.add_column('therapy_sessions', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('therapy_sessions', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('therapy_sessions_modified_by_fkey'), 'therapy_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'therapy_sessions', 'users', ['updated_by'], ['id'])
    op.drop_column('therapy_sessions', 'modified_at')
    op.drop_column('therapy_sessions', 'modified_by')
    op.add_column('user_preferences', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('user_preferences', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('user_preferences', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('updated_by', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_by')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_by')
    op.drop_column('user_preferences', 'is_active')
    op.drop_column('user_preferences', 'updated_by')
    op.drop_column('user_preferences', 'created_by')
    op.add_column('therapy_sessions', sa.Column('modified_by', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('therapy_sessions', sa.Column('modified_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'therapy_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('therapy_sessions_modified_by_fkey'), 'therapy_sessions', 'users', ['modified_by'], ['id'])
    op.drop_column('therapy_sessions', 'updated_by')
    op.drop_column('therapy_sessions', 'updated_at')
    op.drop_column('roles', 'is_default')
    op.drop_column('relief_sessions', 'updated_by')
    op.drop_column('relief_sessions', 'created_by')
    op.drop_column('quick_reliefs', 'updated_by')
    op.drop_column('quick_reliefs', 'created_by')
    op.drop_column('payments', 'is_active')
    op.drop_column('payments', 'updated_by')
    op.drop_column('payments', 'created_by')
    op.drop_column('clinics', 'updated_by')
    op.drop_column('clinics', 'updated_at')
    op.drop_column('clinics', 'created_by')
    op.drop_column('clinics', 'created_at')
    op.drop_column('clinics', 'is_active')
    op.drop_column('chat_questions', 'is_active')
    op.drop_column('chat_options', 'updated_by')
    op.drop_column('chat_options', 'updated_at')
    op.drop_column('chat_options', 'created_by')
    op.drop_column('chat_options', 'created_at')
    op.drop_column('chat_options', 'is_active')
    op.drop_column('awards', 'updated_by')
    op.drop_column('awards', 'updated_at')
    op.drop_column('awards', 'created_by')
    op.drop_column('awards', 'created_at')
    op.drop_column('awards', 'is_active')
    op.drop_column('appointments', 'updated_by')
    op.drop_column('appointments', 'updated_at')
    op.drop_column('appointments', 'created_by')
    op.drop_column('appointments', 'is_active')
    # ### end Alembic commands ###
