"""add_icon_to_roles

Revision ID: 4fa152d16bae
Revises: 0ed7998f0ebc
Create Date: 2026-06-17 19:10:33.877108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fa152d16bae'
down_revision = '0ed7998f0ebc'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    if 'icon' not in {c['name'] for c in inspector.get_columns('roles')}:
        op.add_column('roles', sa.Column('icon', sa.String(length=50), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'icon')
    # ### end Alembic commands ###
