"""create_chat_tables

Revision ID: 73dcd55b16b5
Revises: 16c38f75bcb7
Create Date: 2026-06-15 16:16:17.701063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73dcd55b16b5'
down_revision = '16c38f75bcb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question_text', sa.String(length=500), nullable=False),
    sa.Column('is_start', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_options',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('option_text', sa.String(length=255), nullable=False),
    sa.Column('next_question_id', sa.Integer(), nullable=True),
    sa.Column('video_group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['next_question_id'], ['chat_questions.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['chat_questions.id'], ),
    sa.ForeignKeyConstraint(['video_group_id'], ['video_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_options')
    op.drop_table('chat_questions')
    # ### end Alembic commands ###
