"""Refactor DoctorAvailability and Appointment to use SlotTimings

Revision ID: a363ff2f13d5
Revises: 27abcfbe7b05
Create Date: 2026-06-18 10:41:43.791770

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a363ff2f13d5'
down_revision = '27abcfbe7b05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('slot_timing_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'appointments', 'slot_timings', ['slot_timing_id'], ['id'])
    # Data migration would be needed here to populate slot_timing_id, then set nullable=False
    op.drop_column('appointments', 'slot_start')
    op.drop_column('appointments', 'slot_end')
    
    op.add_column('doctor_availability', sa.Column('slot_timing_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'doctor_availability', 'slot_timings', ['slot_timing_id'], ['id'])
    # Data migration would be needed here to populate slot_timing_id, then set nullable=False
    op.drop_column('doctor_availability', 'start_time')
    op.drop_column('doctor_availability', 'day_of_week')
    op.drop_column('doctor_availability', 'end_time')
    op.drop_column('doctor_availability', 'slot_duration_minutes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_availability', sa.Column('slot_duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('doctor_availability', sa.Column('end_time', postgresql.TIME(), autoincrement=False, nullable=False))
    op.add_column('doctor_availability', sa.Column('day_of_week', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('doctor_availability', sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'doctor_availability', type_='foreignkey')
    op.drop_column('doctor_availability', 'slot_timing_id')
    op.add_column('appointments', sa.Column('slot_end', postgresql.TIME(), autoincrement=False, nullable=False))
    op.add_column('appointments', sa.Column('slot_start', postgresql.TIME(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'slot_timing_id')
    # ### end Alembic commands ###
