"""add audit fields to remaining business tables

Revision ID: a784ffed457e
Revises: 881ee87d7d95
Create Date: 2026-06-17 15:25:59.496631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a784ffed457e'
down_revision = '881ee87d7d95'
branch_labels = None
depends_on = None


def _add_if_missing(inspector, table, col, col_type, **kwargs):
    existing = {c['name'] for c in inspector.get_columns(table)}
    if col not in existing:
        op.add_column(table, sa.Column(col, col_type, nullable=True, **kwargs))


def upgrade():
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    _add_if_missing(inspector, 'appointments', 'is_active', sa.Boolean())
    _add_if_missing(inspector, 'appointments', 'created_by', sa.Integer())
    _add_if_missing(inspector, 'appointments', 'updated_at', sa.DateTime(), server_default=sa.text('now()'))
    _add_if_missing(inspector, 'appointments', 'updated_by', sa.Integer())

    _add_if_missing(inspector, 'awards', 'is_active', sa.Boolean())
    _add_if_missing(inspector, 'awards', 'created_at', sa.DateTime(), server_default=sa.text('now()'))
    _add_if_missing(inspector, 'awards', 'created_by', sa.Integer())
    _add_if_missing(inspector, 'awards', 'updated_at', sa.DateTime())
    _add_if_missing(inspector, 'awards', 'updated_by', sa.Integer())

    _add_if_missing(inspector, 'chat_options', 'is_active', sa.Boolean())
    _add_if_missing(inspector, 'chat_options', 'created_at', sa.DateTime(), server_default=sa.text('now()'))
    _add_if_missing(inspector, 'chat_options', 'created_by', sa.Integer())
    _add_if_missing(inspector, 'chat_options', 'updated_at', sa.DateTime())
    _add_if_missing(inspector, 'chat_options', 'updated_by', sa.Integer())

    _add_if_missing(inspector, 'chat_questions', 'is_active', sa.Boolean())

    _add_if_missing(inspector, 'clinics', 'is_active', sa.Boolean())
    _add_if_missing(inspector, 'clinics', 'created_at', sa.DateTime(), server_default=sa.text('now()'))
    _add_if_missing(inspector, 'clinics', 'created_by', sa.Integer())
    _add_if_missing(inspector, 'clinics', 'updated_at', sa.DateTime())
    _add_if_missing(inspector, 'clinics', 'updated_by', sa.Integer())

    _add_if_missing(inspector, 'consultation_types', 'is_active', sa.Boolean())
    _add_if_missing(inspector, 'consultation_types', 'created_at', sa.DateTime(), server_default=sa.text('now()'))
    _add_if_missing(inspector, 'consultation_types', 'created_by', sa.Integer())
    _add_if_missing(inspector, 'consultation_types', 'updated_at', sa.DateTime())
    _add_if_missing(inspector, 'consultation_types', 'updated_by', sa.Integer())

    _add_if_missing(inspector, 'payments', 'created_by', sa.Integer())
    _add_if_missing(inspector, 'payments', 'updated_by', sa.Integer())
    _add_if_missing(inspector, 'payments', 'is_active', sa.Boolean())

    _add_if_missing(inspector, 'quick_reliefs', 'created_by', sa.Integer())
    _add_if_missing(inspector, 'quick_reliefs', 'updated_by', sa.Integer())

    _add_if_missing(inspector, 'relief_sessions', 'created_by', sa.Integer())
    _add_if_missing(inspector, 'relief_sessions', 'updated_by', sa.Integer())

    _add_if_missing(inspector, 'user_preferences', 'created_by', sa.Integer())
    _add_if_missing(inspector, 'user_preferences', 'updated_by', sa.Integer())
    _add_if_missing(inspector, 'user_preferences', 'is_active', sa.Boolean())

    _add_if_missing(inspector, 'users', 'created_by', sa.Integer())
    _add_if_missing(inspector, 'users', 'updated_at', sa.DateTime(), server_default=sa.text('now()'))
    _add_if_missing(inspector, 'users', 'updated_by', sa.Integer())
    _add_if_missing(inspector, 'users', 'is_active', sa.Boolean())


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'updated_by')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_by')
    op.drop_column('user_preferences', 'is_active')
    op.drop_column('user_preferences', 'updated_by')
    op.drop_column('user_preferences', 'created_by')
    op.drop_column('relief_sessions', 'updated_by')
    op.drop_column('relief_sessions', 'created_by')
    op.drop_column('quick_reliefs', 'updated_by')
    op.drop_column('quick_reliefs', 'created_by')
    op.drop_column('payments', 'is_active')
    op.drop_column('payments', 'updated_by')
    op.drop_column('payments', 'created_by')
    op.drop_column('consultation_types', 'updated_by')
    op.drop_column('consultation_types', 'updated_at')
    op.drop_column('consultation_types', 'created_by')
    op.drop_column('consultation_types', 'created_at')
    op.drop_column('consultation_types', 'is_active')
    op.drop_column('clinics', 'updated_by')
    op.drop_column('clinics', 'updated_at')
    op.drop_column('clinics', 'created_by')
    op.drop_column('clinics', 'created_at')
    op.drop_column('clinics', 'is_active')
    op.drop_column('chat_questions', 'is_active')
    op.drop_column('chat_options', 'updated_by')
    op.drop_column('chat_options', 'updated_at')
    op.drop_column('chat_options', 'created_by')
    op.drop_column('chat_options', 'created_at')
    op.drop_column('chat_options', 'is_active')
    op.drop_column('awards', 'updated_by')
    op.drop_column('awards', 'updated_at')
    op.drop_column('awards', 'created_by')
    op.drop_column('awards', 'created_at')
    op.drop_column('awards', 'is_active')
    op.drop_column('appointments', 'updated_by')
    op.drop_column('appointments', 'updated_at')
    op.drop_column('appointments', 'created_by')
    op.drop_column('appointments', 'is_active')
    # ### end Alembic commands ###
