"""add audit fields

Revision ID: b3bec455c884
Revises: e6f3a82d4c91
Create Date: 2026-06-15 18:07:04.037154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3bec455c884'
down_revision = 'e6f3a82d4c91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_availability', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('doctor_availability', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('doctor_availability', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('doctor_availability', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('doctor_availability', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_column('doctor_availability', 'is_available')
    op.add_column('doctors', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('doctors', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('doctors', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('doctors', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('expertise', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('expertise', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('expertise', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('expertise', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('expertise', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('languages', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('languages', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('languages', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('languages', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('languages', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('specialties', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('specialties', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('specialties', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('specialties', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('specialties', 'is_active')
    op.drop_column('specialties', 'updated_by')
    op.drop_column('specialties', 'created_by')
    op.drop_column('specialties', 'updated_at')
    op.drop_column('languages', 'is_active')
    op.drop_column('languages', 'updated_by')
    op.drop_column('languages', 'created_by')
    op.drop_column('languages', 'updated_at')
    op.drop_column('languages', 'created_at')
    op.drop_column('expertise', 'is_active')
    op.drop_column('expertise', 'updated_by')
    op.drop_column('expertise', 'created_by')
    op.drop_column('expertise', 'updated_at')
    op.drop_column('expertise', 'created_at')
    op.drop_column('doctors', 'is_active')
    op.drop_column('doctors', 'updated_by')
    op.drop_column('doctors', 'created_by')
    op.drop_column('doctors', 'updated_at')
    op.add_column('doctor_availability', sa.Column('is_available', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('doctor_availability', 'is_active')
    op.drop_column('doctor_availability', 'updated_by')
    op.drop_column('doctor_availability', 'created_by')
    op.drop_column('doctor_availability', 'updated_at')
    op.drop_column('doctor_availability', 'created_at')
    # ### end Alembic commands ###
