"""restore_key_in_wellness

Revision ID: de073083540a
Revises: 21eed69bbd76
Create Date: 2026-06-15 20:07:14.130831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de073083540a'
down_revision = '21eed69bbd76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wellness_sessions', sa.Column('key', sa.String(length=100), nullable=True))
    
    # Data migration: populate with unique keys
    op.execute("UPDATE wellness_sessions SET key = 'session_' || id")
    
    op.alter_column('wellness_sessions', 'key', nullable=False)
    op.create_unique_constraint(None, 'wellness_sessions', ['key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wellness_sessions', type_='unique')
    op.drop_column('wellness_sessions', 'key')
    # ### end Alembic commands ###
