"""Add DayOfWeek model

Revision ID: e0b33d6828f1
Revises: 29d9dc6c6b4a
Create Date: 2026-06-18 10:25:07.716374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0b33d6828f1'
down_revision = '29d9dc6c6b4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('days_of_week',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day'),
    sa.UniqueConstraint('day_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('days_of_week')
    # ### end Alembic commands ###
