"""add_fields_to_doctor_leaves

Revision ID: fcf1701ebc35
Revises: a4b5c6d7e8f9
Create Date: 2026-06-30 15:50:13.433981

"""
from alembic import op
import sqlalchemy as sa
from app.db.types import GUID


# revision identifiers, used by Alembic.
revision = 'fcf1701ebc35'
down_revision = 'a4b5c6d7e8f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_leave_slots',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('leave_id', GUID(), nullable=False),
    sa.Column('slot_timing_id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['leave_id'], ['doctor_leaves.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['slot_timing_id'], ['slot_timings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_leave_slots_leave_id'), 'doctor_leave_slots', ['leave_id'], unique=False)
    op.create_index(op.f('ix_doctor_leave_slots_slot_timing_id'), 'doctor_leave_slots', ['slot_timing_id'], unique=False)
    op.add_column('doctor_leaves', sa.Column('leave_type', sa.String(length=20), nullable=False, server_default='single'))
    op.add_column('doctor_leaves', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('doctor_leaves', sa.Column('end_date', sa.Date(), nullable=True))
    op.add_column('doctor_leaves', sa.Column('start_time', sa.Time(), nullable=True))
    op.add_column('doctor_leaves', sa.Column('end_time', sa.Time(), nullable=True))
    op.add_column('doctor_leaves', sa.Column('notes', sa.Text(), nullable=True))
    op.alter_column('doctor_leaves', 'leave_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('doctor_leaves', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.create_index(op.f('ix_doctor_leaves_start_date'), 'doctor_leaves', ['start_date'], unique=False)
    op.create_index(op.f('ix_doctor_leaves_status'), 'doctor_leaves', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_doctor_leaves_status'), table_name='doctor_leaves')
    op.drop_index(op.f('ix_doctor_leaves_start_date'), table_name='doctor_leaves')
    op.alter_column('doctor_leaves', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('doctor_leaves', 'leave_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('doctor_leaves', 'notes')
    op.drop_column('doctor_leaves', 'end_time')
    op.drop_column('doctor_leaves', 'start_time')
    op.drop_column('doctor_leaves', 'end_date')
    op.drop_column('doctor_leaves', 'start_date')
    op.drop_column('doctor_leaves', 'leave_type')
    op.drop_index(op.f('ix_doctor_leave_slots_slot_timing_id'), table_name='doctor_leave_slots')
    op.drop_index(op.f('ix_doctor_leave_slots_leave_id'), table_name='doctor_leave_slots')
    op.drop_table('doctor_leave_slots')
    # ### end Alembic commands ###
